---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-management
  labels:
    app: process-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process-management
  template:
    metadata:
      labels:
        app: process-management
    spec:
      containers:
        - name: process-management
          image: username/process-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management
  labels:
    app: task-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-management
  template:
    metadata:
      labels:
        app: task-management
    spec:
      containers:
        - name: task-management
          image: username/task-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: process-management
  labels:
    app: process-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: process-management


---


apiVersion: v1
kind: Service
metadata:
  name: task-management
  labels:
    app: task-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: task-management

